---
- name: Unmount client mount path
  ansible.posix.mount:
    path: "{{ item.path }}"
    state: unmounted
  become: true
  when: beegfs_enable.client | bool
  loop: "{{ beegfs_client_mounts | default([]) }}"


- name: (Backward compatible) Stop and disable BeeGFS storage service
  ansible.builtin.service:
    name: "beegfs-storage@{{ item.key }}"
    enabled: false
    state: stopped
  become: true
  when:
    - beegfs_enable.oss | bool
    - item.dev is defined
  loop: "{{ beegfs_oss | dict2items }}"

- name: Stop and disable BeeGFS storage services
  ansible.builtin.service:
    name: "beegfs-storage@{{ item.key }}"
    enabled: false
    state: stopped
  become: true
  when: beegfs_enable.oss | bool
  loop: "{{ beegfs_oss | dict2items }}"

- name: Stop and disable BeeGFS server services
  ansible.builtin.service:
    name: "{{ item.name }}"
    enabled: false
    state: stopped
  become: true
  when: item.enable | bool
  loop:
    - { name: beegfs-mgmtd, enable: "{{ beegfs_enable.mgmt }}" }
    - { name: beegfs-meta, enable: "{{ beegfs_enable.meta }}" }
    - { name: beegfs-mon, enable: "{{ beegfs_enable.mon }}" }
    - { name: beegfs-oss-tuning, enable: "{{ beegfs_enable.tuning }}" }

- name: Clear storeStorageDirectory
  ansible.builtin.lineinfile:
    path: "/etc/beegfs/{{ item.key }}.d/beegfs-storage.conf"
    regexp: "^storeStorageDirectory"
    line: "storeStorageDirectory ="
  loop: "{{ beegfs_oss | dict2items }}"
  become: true
  when: beegfs_enable.oss | bool

- name: Clear storeFsUUID
  ansible.builtin.lineinfile:
    path: "/etc/beegfs/{{ item.key }}.d/beegfs-storage.conf"
    regexp: "^storeFsUUID"
    line: "storeFsUUID ="
  loop: "{{ beegfs_oss | dict2items }}"
  become: true
  when: beegfs_enable.oss | bool

- name: Unmount BeeGFS oss paths if mounted
  vars:
    oss_path: "{{ item.path | default(beegfs_oss_path_prefix + item.1) }}"
  ansible.posix.mount:
    path: "{{ oss_path }}"
    state: unmounted
  become: true
  loop: "{{ beegfs_oss | dict2items | subelements('value.devices') }}"
  loop_control:
    label: "{{ item.1 }}"
  when:
    - beegfs_enable.oss | bool

- name: Remove all beegfs oss folders
  vars:
    oss_path: "{{ beegfs_oss_path_prefix + item.1 }}"
  ansible.builtin.file:
    path: "{{ oss_path }}"
    state: absent
  become: true
  loop: "{{ beegfs_oss | dict2items | subelements('value.devices') }}"
  loop_control:
    label: "{{ item.1 }}"
  when:
    - beegfs_enable.oss | bool

- name: Ensure meta device is not currently mounted
  become: true
  ansible.posix.mount:
    path: "{{ beegfs_meta_path }}"
    state: unmounted
  when:
    - beegfs_enable.meta | default(false) | bool
    - beegfs_meta_dev is defined
    - beegfs_meta_dev != None

- name: Remove other beegfs folders
  ansible.builtin.file:
    path: "{{ item.name }}"
    state: absent
  become: true
  when: item.enable | bool
  loop:
    - { name: "{{ beegfs_meta_path }}", enable: "{{ beegfs_enable.meta }}" }
    - { name: "{{ beegfs_mgmt_path }}", enable: "{{ beegfs_enable.mgmt }}" }
...
