---
- name: Clear storeStorageDirectory
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: "^storeStorageDirectory"
    line: "storeStorageDirectory        ="
  become: yes

- name: Unmount beegfs data
  mount:
    path: "{{ beegfs_path_oss }}/{{ item }}"
    state: absent
  become: yes
  with_items:
  - "{{ beegfs_dev_oss }}"
  when: beegfs_enable.oss

- name: Format filesystem
  filesystem:
    dev: "{{ item }}"
    fstype: "{{ beegfs_fstype }}"
    force: yes
  become: yes
  with_items:
  - "{{ beegfs_dev_oss }}"
  when:
  - beegfs_enable.oss
  - beegfs_dev_oss is defined

- name: Remove all beegfs folders
  file:
    path: /data/beegfs/
    state: absent
  become: yes
...
