---
- name: Unmount client mount path
  mount:
    path: "{{ item.beegfs_path_client }}"
    state: unmounted
  become: yes 
  when: beegfs_enable.client | bool
  with_items: "{{ beegfs_client_confs }}"

- name: Disable and stop BeeGFS server services
  service:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  become: yes
  when: item.enable | bool
  with_items:
  - { name: beegfs-mgmtd, enable: "{{ beegfs_enable.mgmt }}" }
  - { name: beegfs-meta, enable: "{{ beegfs_enable.meta }}" }
  - { name: beegfs-storage, enable: "{{ beegfs_enable.oss }}" }
  - { name: beegfs-admon, enable: "{{ beegfs_enable.admon }}" }
  - { name: beegfs-client, enable: "{{ beegfs_enable.client }}" }
  - { name: beegfs-helperd, enable: "{{ beegfs_enable.client }}" }

- name: Clear storeStorageDirectory
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: "^storeStorageDirectory"
    line: "storeStorageDirectory ="
  become: yes
  when: beegfs_enable.oss | bool

- name: Unmount BeeGFS oss paths if mounted
  mount:
    path: "{{ item }}"
    state: unmounted
  become: yes
  with_items:
  - "{{ beegfs_path_oss }}"
  when:
  - beegfs_enable.oss | bool
  - beegfs_dev_oss is defined

- name: Remove all beegfs oss folders
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  when: beegfs_enable.oss | bool
  with_items: "{{ beegfs_path_oss }}"

- name: Remove other beegfs folders
  file:
    path: "{{ item.name }}"
    state: absent
  become: yes
  when: item.enable | bool
  with_items:
  - { name: "{{ beegfs_path_meta }}", enable: "{{ beegfs_enable.meta }}" } 
  - { name: "{{ beegfs_path_mgmt }}", enable: "{{ beegfs_enable.mgmt }}" }
...
