---

- name: Check for ofed_info
  ansible.builtin.command: "ofed_info -s"
  register: _ofed_info
  failed_when: false
  changed_when: false

- name: Determine if ofed is in use
  ansible.builtin.set_fact:
    beegfs_ofed_installed: "{{ _ofed_info.rc == 0 }}"

- name: Generate beegfs-client-build.mk
  become: true
  ansible.builtin.template:
    dest: /etc/beegfs/beegfs-client-build.mk
    src: beegfs-client-build.mk.j2
    mode: "0644"
  when: beegfs_enable.client | bool


- name: install | Build host-specific list of required beegfs packages
  become: true
  tags: install
  ansible.builtin.set_fact:
    beegfs_pkglist: "{{ beegfs_pkglist | default([]) + item.value }}"
  loop: "{{ beegfs_packages | dict2items }}"
  when: (beegfs_enable.get(item.key, false))

- name: install | Install required beegfs packages
  become: true
  tags: install
  ansible.builtin.dnf:
    name: "{{ beegfs_pkglist | reject('eq', '') }}"
    state: "{{ beegfs_package_action }}"
    install_weak_deps: false # avoids getting recommended packages
  when: beegfs_pkglist | length > 0

- name: install | Install RDMA packages
  become: true
  tags: install
  ansible.builtin.package:
    name: "{{ beegfs_distro_vars[ansible_os_family]['rdma_dev_pkgs'] }}"
    state: "{{ beegfs_package_action }}"
  when: beegfs_rdma | bool
