---
- name: Create BeeGFS cluster
  ansible.builtin.import_tasks: create.yml
  when: beegfs_state | lower == "present"

- name: Destroy BeegFS cluster
  ansible.builtin.import_tasks: destroy.yml
  when: beegfs_state | lower == "absent"
...
