---
- name: Install packages for BeeGFS metadata server
  package:
    name: beegfs-meta
    state: present
  become: yes
  notify: Enable and start BeeGFS meta service

- name: Create directory for BeeGFS metadata
  file:
    path: "{{ beegfs_path_meta }}"
    state: directory
  become: yes
  notify: Enable and start BeeGFS meta service

- name: Prepare metadata block storage
  block:
  - name: Ensure storage device is not currently mounted
    mount:
      path: "{{ beegfs_path_meta }}"
      state: unmounted
    notify: Enable and start BeeGFS meta service
  - name: Format filesystem
    filesystem:
      dev: "{{ beegfs_dev_meta }}"
      fstype: "{{ beegfs_fstype }}"
      force: "{{ beegfs_force_format }}"
    notify: Enable and start BeeGFS meta service
  - name: Mount filesystem
    mount:
      src: "{{ beegfs_dev_meta }}"
      path: "{{ beegfs_path_meta }}"
      fstype: "{{ beegfs_fstype }}"
      state: mounted
    notify: Enable and start BeeGFS meta service
  become: yes
  when: beegfs_dev_meta is defined

- name: Run metadata service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ beegfs_path_meta }} -m {{ beegfs_host_mgmt }} -f"
  args:
    creates: "{{ beegfs_path_meta }}/originalNodeID"
  become: yes
  notify: Enable and start BeeGFS meta service

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: yes
  notify: Enable and start BeeGFS meta service
