---
- name: Install packages for BeeGFS metadata server
  package:
    name: beegfs-meta
    state: present
  become: yes
  notify: Restart BeeGFS meta service

- name: Create directory for BeeGFS metadata
  file:
    path: "{{ beegfs_meta.path }}"
    state: directory
  become: yes
  notify: Restart BeeGFS meta service

- name: Prepare metadata block storage
  block:
  vars:
    meta_fstype: "{{ beegfs_meta.fstype | default(beegfs_fstype) }}"
  - name: Ensure storage device is not currently mounted
    mount:
      path: "{{ beegfs_meta.path }}"
      state: unmounted
    notify: Restart BeeGFS meta service
  - name: Format filesystem
    filesystem:
      dev: "{{ beegfs_meta.dev }}"
      fstype: "{{ meta_fstype }}"
      force: "{{ beegfs_force_format }}"
    notify: Restart BeeGFS meta service
  - name: Mount filesystem
    mount:
      src: "{{ beegfs_meta.dev }}"
      path: "{{ beegfs_meta.path }}"
      fstype: "{{ meta_fstype }}"
      state: mounted
    notify: Restart BeeGFS meta service
  become: yes
  when:
  - beegfs_meta.dev is defined
  - beegfs_meta.dev != None

- name: Run metadata service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ beegfs_meta.path }} -m {{ beegfs_mgmt.host }} -f"
  args:
    creates: "{{ beegfs_meta.path }}/originalNodeID"
  become: yes
  notify: Restart BeeGFS meta service

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: yes
  notify: Restart BeeGFS meta service
...
