---
- name: Install packages for BeeGFS object storage server
  package:
    name: beegfs-storage
    state: present
  become: yes

- name: Ensures BeeGFS storage service is not running
  service:
    name: beegfs-storage
    state: stopped
  become: yes

- name: Prepare storage devices
  block:
  - name: Ensure storage device is not currently mounted
    mount:
      path: "{{ beegfs_path_oss }}/{{ item }}"
      state: unmounted
    with_items:
    - "{{ beegfs_dev_oss }}"
  - name: Format filesystem
    filesystem:
      dev: "{{ beegfs_path_dev }}/{{ item }}"
      fstype: "{{ beegfs_fstype }}"
    with_items:
    - "{{ beegfs_dev_oss }}"
  - name: Mount filesystem
    mount:
      src: "{{ beegfs_path_dev }}/{{ item }}"
      path: "{{ beegfs_path_oss }}/{{ item }}"
      fstype: "{{ beegfs_fstype }}"
      state: mounted
    with_items:
    - "{{ beegfs_dev_oss }}"
  become: yes
  when: beegfs_dev_oss is defined

- name: Run storage service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-storage -p {{ beegfs_path_oss }}/{{ item }} -m {{ beegfs_host_mgmt }} -f"
  args:
    creates: "{{ item }}/originalNodeID"
  with_items: "{{ beegfs_dev_oss }}"
  become: yes

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: yes
...
