---
- name: Install packages for BeeGFS object storage server
  package:
    name: beegfs-storage
    state: present
  become: yes

- name: Create a list of devices that are mounted
  set_fact:
    mounted_path_dev_items: "{{ ansible_mounts | map(attribute='device') | list }}"

- name: Ensures BeeGFS storage service is not running
  service:
    name: beegfs-storage
    state: stopped
  become: yes

- name: Prepare storage devices
  block:
  - name: Attempt to format if the device is not mounted
    vars:
      path_dev_item: "{{ beegfs_path_dev }}/{{ item }}"
    filesystem:
      dev: "{{ path_dev_item }}"
      fstype: "{{ beegfs_fstype }}"
    when: path_dev_item not in mounted_path_dev_items
    with_items:
    - "{{ beegfs_dev_oss }}"
  - name: Mount filesystem, fail if the fstype doesn't match
    mount:
      src: "{{ beegfs_path_dev }}/{{ item }}"
      path: "{{ beegfs_path_oss }}/{{ item }}"
      fstype: "{{ beegfs_fstype }}"
      state: mounted
    with_items:
    - "{{ beegfs_dev_oss }}"
  become: yes
  when: beegfs_dev_oss is defined

- name: Run storage service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-storage -p {{ beegfs_path_oss }}/{{ item }} -m {{ beegfs_host_mgmt }} -f"
  args:
    creates: "{{ beegfs_path_oss }}/{{ item }}/originalNodeID"
  with_items: "{{ beegfs_dev_oss }}"
  become: yes

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: yes
...
