---
- name: Ensure RDMA packages are installed
  package:
    name:
    - "librdmacm"
    - "libibmad"
    - "libibumad"
    - "rdma-core"
    - "libibverbs"
    - "libibverbs-utils"
    state: present
  become: yes

- name: Ensure RDMA kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
  - "ib_umad"
  - "ib_uverbs"
  - "rdma_ucm"
...
