---
# BeeGFS tuning parameters
# from https://www.beegfs.io/wiki/StorageServerTuning
- name: BeeGFS tuning parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
  - {key: 'vm.dirty_background_ratio', value: '5'}
  - {key: 'vm.dirty_ratio', value: '20'}
  - {key: 'vm.vfs_cache_pressure', value: '50'}
  - {key: 'vm.min_free_kbytes', value: '262144'}
  - {key: 'vm.zone_reclaim_mode', value: '1'}
  become: yes

- name: Copy beegfs-tuning.sh to /opt/beegfs/
  template:
    src: beegfs-tuning.sh.j2
    dest: /opt/beegfs/beegfs-tuning.sh
    mode: a+x
  become: yes
  notify: Restart BeeGFS tuning service


- name: Copy beegfs-tuning.service to /etc/systemd/system/
  copy:
    src: beegfs-tuning.service
    dest: /etc/systemd/system/
  become: yes
  notify:
  - Restart BeeGFS tuning service
...
