---
- name: Restart BeeGFS mgmt service
  service:
    name: beegfs-mgmtd
    state: restarted
  become: true
  when: beegfs_enable.mgmt | bool

- name: Restart BeeGFS meta service
  service:
    name: beegfs-meta
    state: restarted
  become: true
  when: beegfs_enable.meta | bool

- name: Restart BeeGFS storage service
  service:
    name: "beegfs-storage@{{ item.port }}"
    state: restarted
  become: true
  with_items: "{{ beegfs_oss }}"
  when: beegfs_enable.oss | bool

- name: Restart BeeGFS admon service
  service:
    name: beegfs-admon
    state: restarted
  become: true
  when: beegfs_enable.admon | bool

- name: Restart BeeGFS client service
  service:
    name: "{{ item }}"
    state: restarted
  become: true
  with_items:
    - beegfs-helperd
    - beegfs-client
  when: beegfs_enable.client | bool
  retries: 3
  delay: 3
  register: result
  until: result is success

- name: Restart BeeGFS tuning service
  systemd:
    name: beegfs-oss-tuning
    daemon-reload: yes
    state: restarted
  become: true
...
