---
- name: Enable and start BeeGFS mgmt service
  service:
    name: beegfs-mgmtd
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.mgmt | bool

- name: Enable and start BeeGFS meta service
  service:
    name: beegfs-meta
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.meta | bool

- name: Enable and start BeeGFS storage service
  service:
    name: beegfs-storage
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.oss | bool
  notify: Ensure that BeeGFS storage service has really started

- name: Ensure that BeeGFS storage service has really started
  service:
    name: beegfs-storage
    state: started
  become: yes
  when: beegfs_enable.oss | bool

- name: Enable and start BeeGFS client service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  become: yes
  with_items:
  - beegfs-helperd
  - beegfs-client
  when: beegfs_enable.client | bool
  retries: 3
  delay: 3
  register: result
  until: result is success

- name: Enable and start BeeGFS admon service
  service:
    name: beegfs-admon
    enabled: yes
    state: restarted
  become: yes
  when: beegfs_enable.admon | bool
...
